### ISSUE TITLE
Breaking change in a minor version update

### ISSUE THREAD

**Issue by verkhoro** [DataDog/java-dogstatsd-client#120]
Hey,
I believe that [changing configuration setup](https://github.com/DataDog/java-dogstatsd-client/pull/94/files#diff-f4b9746cffe53d8778d5b04a486a2b2d) from `NonBlockingStatsDClient` to `NonBlockingStatsDClientBuilder` is a breaking change which wasn't communicated in release notes and through the major version bump. I would have to fix our code if you bumped the major version, so I am going to do that now, but at least I wouldn't discover that in staging.

I don't expect any action at this point. Cheers

**Comment by truthbk** [comment]
Hi @verkhoro, the old constructors are still available. The builder is the new recommended way to build your clients, but the old constructors are still available, this was left as so to avoid breaking stuff. Did you experience breakage in your applications after a version bump? If so, we should fix it.

**Comment by verkhoro** [comment]
Het @truthbk, the old constructors have been removed in `src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java`. My prior link to the diff didn't focus on this specific file, so it wasn't clear what the issue is.

**Comment by truthbk** [comment]
@verkhoro all the old constructors are still there, they just rely on the builder internally and have been marked as deprecated. Here are a few examples: https://github.com/DataDog/java-dogstatsd-client/blob/master/src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java#L377-L430

And we have a bunch of tests to ensure those old constructors are still yielding valid clients, for example: https://github.com/DataDog/java-dogstatsd-client/blob/master/src/test/java/com/timgroup/statsd/NonBlockingStatsDClientTest.java#L435-L443

Let me know if something remains unclear.

You should be able to continue using your old constructors transparently.
