### ISSUE TITLE
Please put back the public Constructors on the NonBlockingStatsDClient!

### ISSUE THREAD

**Issue by golfingal72** [DataDog/java-dogstatsd-client#173]
We have a large legacy system that used the java-statsd-client.  I am trying to integrate the datadog statsd client into a new code base and tried using version 3.0.0 and the public constructors were removed from the NonBlockingStatsDClient [the new code relies on functionality in the legacy packages]. I am unable to use the current version of the client because the constructors were removed, so I am trying to use the 2.x versions of your code. I will be forever out of date with any code updates you make in the future. 
Can you please put the public constructors back! including:
public NonBlockingStatsDClient(String prefix, String hostname, int port, StatsDClientErrorHandler errorHandler);

I am assuming that I can use the datadog statsd client to write to legacy statsd servers. Is that true?  
We still need to run the legacy code and send data to a legacy statsd server and I can't go and change all that code.
If not, I am going to have to copy your code and rename the packages so that I can maintain the legacy functionality.

IMHO, it was kind of a mistake that you used the same package names as the existing java-statsd-client because unknowingly consumers could have 2 copies of the same code in their deployment and get unexpected results [That would exactly have happened to me unless the problem with the constructors didn't show itself]. In hindsight, it may have been better to create your own package names so the legacy code could still function.

**Comment by golfingal72** [comment]
Aargh, you also changed the interface specification of the original java-statsd-client... I have no recourse but to copy your whole library

**Comment by vickenty** [comment]
Thank you for bringing this up. I'm sorry that you couldn't use the library directly.

The package name conflict is indeed unfortunate. As you say, the right time to change the name was when the project was forked. Renaming the package is still correct thing to do, our team will investigate if we can do this in a non-disruptive way.

As you noted, bringing back the constructors would not be sufficient to provide compatibility with the original statsd code, so there is little point in doing so now.

Feel free to re-open the issue if you have any further questions.
