### ISSUE TITLE
TCP support

### ISSUE THREAD

**Issue by jebeaudet** [DataDog/java-dogstatsd-client#186]
Hi!

Do you have any plans to support TCP instead of UDP to send metrics to StatsD? Or would you be open for a PR tu support it?

**Comment by vickenty** [comment]
Hi, @jebeaudet, thank you for reaching out. I'm sorry, but TCP support is not currently on the radar. We'd need to carefully consider implications for other dogstatsd clients we support, as well as the datadog agent, so I don't think that a PR here is where we would start.

**Comment by jebeaudet** [comment]
Hi @vickenty 

While I understand DataDog maintains this library, isn't the purpose of it to support statsd as a whole and not just DataDog implementation? I have a need for a TCP implementation for Hosted Graphite StatsD and surprisingly, there is no client supporting this.

I know I can fork it and do it myself but I'd rather make the contribution upstream so that others can beneficiate from it. 

You mention a PR here is not where you would start, where would that be?

Thanks!

**Comment by vickenty** [comment]
I'm afraid this is a Datadog-specific implementation, we wouldn't consider features that don't work with our product. Sorry.
