### ISSUE TITLE
Should ByteBuffer be cleared when exceptions are thrown?

### ISSUE THREAD

**Issue by shawnsong** [DataDog/java-dogstatsd-client#198]
Should we clear the buffer [here](https://github.com/DataDog/java-dogstatsd-client/blob/ad4daeafa7cb6a6a906d8f9791b4da9eb661f8ef/src/main/java/com/timgroup/statsd/StatsDSender.java#L114) as well? 

When an exception is thrown from `clientChannel.write(buffer);`, the [_flipped_ ](https://github.com/DataDog/java-dogstatsd-client/blob/ad4daeafa7cb6a6a906d8f9791b4da9eb661f8ef/src/main/java/com/timgroup/statsd/StatsDSender.java#L91)`buffer` is put back to the `pool` in the next run of the while loop without being _cleared_. Is this expected?

**Comment by vickenty** [comment]
Thank you for bringing this up!
