### ISSUE TITLE
Overhead in message aggregation

### ISSUE THREAD

**Issue by pbarsotti-glovo** [DataDog/java-dogstatsd-client#208]
We see a noticeable overhead in the aggregation mechanism which is driving up our CPU values, specially when we produce a high number of metrics.

![image](https://user-images.githubusercontent.com/57904011/208481666-c2559ec9-b9b5-4870-8453-36a085334d53.png)

We understand that a fix was released in 4.1.0 (#194) but another one is still pending to be released (#203). Is there any plan to make a release anytime soon to include this improvement?

**Comment by vickenty** [comment]
Hi @pbarsotti-glovo, thank you for using Datadog.

v4.2.0 was released today which includes the performance improvements from #203.
