### ISSUE TITLE
Documentation mismatch: resolve() is protected

### ISSUE THREAD

**Issue by jarl-dk** [DataDog/java-dogstatsd-client#209]
The documentation says that `resolve()` can be used to create a client:
https://github.com/DataDog/java-dogstatsd-client/blob/76e0e719b91ac7748788103b6dc04f71b855911c/README.md?plain=1#L77

However this method is protected. I don't know if the intention is that this should be public or this alternative way in the documentaiton should be removed.

**Comment by vickenty** [comment]
Thank you!
