### ISSUE TITLE
Help needed: Increment counter specified times

### ISSUE THREAD

**Issue by pvpkiran** [DataDog/java-dogstatsd-client#21]
Hi,
  I want to know how can I increase a counter with a specified value. For example if I need to increase the counter by 300, I can do 
```
for(int i=0;i<300;i++)
            statsDClient.increment("pushed.from.inventory")
```

but is it possible to do without a loop?

Thanks

**Comment by masci** [comment]
Hi @pvpkiran,

actually the feature you need is quite easy to implement, I'll add it to my queue.
If you want to give it a shot in the meantime and submit a  PR, contributions are more than welcome!

**Comment by yeenow123** [comment]
Can you not just use

public void count(final String aspect, final long delta, final String... tags) 

Or is a convenience method required?

**Comment by pvpkiran** [comment]
Hi,
  This is what I am using right now 
`count("prefix", count).` 
I don't think a convenience method is necessary.

Cheers

**Comment by masci** [comment]
Good to know that works for you! Closing this then.
