### ISSUE TITLE
The Canonical home should probably not be a fork

### ISSUE THREAD

**Issue by donato** [DataDog/java-dogstatsd-client#22]
It prevents us from being able to search them.

![screen shot 2016-12-06 at 11 25 29 am](https://cloud.githubusercontent.com/assets/939778/20933667/c98a1b5a-bba6-11e6-8391-f4173993ae64.png)

**Comment by irabinovitch** [comment]
@ovesh Any thoughts here? We had discussed transferring the repo rather than forking at one point, but I believe the Indeed team had some concerns.

**Comment by ovesh** [comment]
I'm ok with transfering it. We're talking about [this procedure](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/), right?

Note that indeedeng's repo is _also_ forked (from tim-group/java-statsd-client), so I don't think it would solve the search problem.

**Comment by ovesh** [comment]
I'm ok with transfering it. We're talking about [this procedure](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/), right?

Note that indeedeng's repo is _also_ forked (from tim-group/java-statsd-client), so I don't think it would solve the search problem.

**Comment by irabinovitch** [comment]
@masci @remh any preferences? Disassociating the fork seems easiest at this point?

**Comment by masci** [comment]
The repo is not a fork anymore, thanks everyone for your feedback.
