### ISSUE TITLE
Multiple Tags contains an extra value

### ISSUE THREAD

**Issue by uncanny25** [DataDog/java-dogstatsd-client#255]
Hi,

In our organization, we use the StatsD client to send metrics to New Relic. We apply multiple tags to our metrics. We noticed unexpected behavior starting with versions after 4.0.0: the first element of our tags array, after calling the StatsD client, always contains an extra randomly generated value resembling a hash. For example, if our tags are: ["name:Daniel", "age:25", "height:170"], they are sent to New Relic in the following modified format: ["name:Daniel | c:a671193653f1cab595c7d55a4ec58efc6edf544aaef87d4fb6b57c270f569f0f", "age:25", "height:170"].

This generated value is always added only to the first element of the tags array. We tested and observed this issue in the following versions:
- 4.4.2
- 4.4.1
- 4.4.0
- 4.3.0
- 4.2.0
- 4.1.0

The solution we found is to temporarily downgrade to the latest stable version, 4.0.0. However, this is only a temporary fix, as future vulnerability issues may arise. It would be ideal to have this issue addressed.

Thanks in advance!

**Comment by vickenty** [comment]
Hi, this extra content is container identifier used for origin detection that was introduced with dogstatsd protocol version v1.2. It can be disabled by calling `originDetectionEnabled(false)` on the client builder.
