### ISSUE TITLE
Does the client reconnect if I restart datadog Agent?

### ISSUE THREAD

**Issue by xiaochuanyu** [DataDog/java-dogstatsd-client#30]
Does the client reconnect if I restart datadog Agent or the Agent is down?
For example, I might do this to upgrade the Agent.

**Comment by jking13** [comment]
StatsD uses the UDP protocol. Since it's "fire and forget" the client has no concept of "connecting" with the agent. The client should act the same whether or not the agent is running, and shouldn't have any problems with an agent restart.

**Comment by masci** [comment]
Closing this, feel free to reopen if you experience any issue with the agent restarting
