### ISSUE TITLE
Event sends, but no event in the dogstatsd.log and not in the DataDog events console

### ISSUE THREAD

**Issue by ishailekach123** [DataDog/java-dogstatsd-client#40]
I succeeded with statsd .recordExecutionTime method with the same statsd client.
Any special configuration is needed?

Code example:
private void recordEndLoadGraph(String routerId, String failReason) {

        String endLoadText = StringUtils.isEmpty(failReason) ? ", success" : ", fail reason: " + failReason;
        Event event = Event.builder().withDate(System.currentTimeMillis()).
                withTitle("LoadGraphEnd").
                withAggregationKey(routerId).
                withAlertType(StringUtils.isEmpty(failReason) ? Event.AlertType.INFO : Event.AlertType.ERROR).
                withPriority(Event.Priority.NORMAL).
                withText("End loading graph, router ID: " + routerId + endLoadText).build();
        statsd.recordEvent(event);
    }

**Comment by ishailekach123** [comment]
It works now

**Comment by tazjin** [comment]
@ishailekach123 did you change anything to make it work?

**Comment by ishailekach123** [comment]
@tazjin I really don't remember but I think that I didn't change and it started to work.

**Comment by tazjin** [comment]
@ishailekach123 Thanks - I figured out what the problem was here anyways, the event body was too large :)

**Comment by ishailekach123** [comment]
@tazjin What is the event body limit size?

**Comment by schilling** [comment]
> @tazjin What is the event body limit size?

At least [NonBlockingStatsDClient](https://github.com/DataDog/java-dogstatsd-client/blob/3b8b35092a005b19bc514cc242bd04ffa9425900/src/main/java/com/timgroup/statsd/NonBlockingStatsDClient.java#L1083)'s limit on the final message size is currently set to 1400 bytes.
