### ISSUE TITLE
recordDistributionValue how it's works?

### ISSUE THREAD

**Issue by tfe2012** [DataDog/java-dogstatsd-client#46]
Hi, 
My code looks like:

StatsDClient statsd1 = new NonBlockingStatsDClient(
                            "",
                            "localhost",
                            8125,
                            new String[] {"good"}
                    );

 statsd1.recordDistributionValue("sdw.lumi.test", 11);

Then I run it, in datadog panel I didn't see any metrics

**Comment by masci** [comment]
The feature is currently in beta and needs to be enabled for your org.
Please reach out to support@datadoghq.com for assistance.

**Comment by tfe2012** [comment]
Yes I made request, they enable me this feature, but it doesn't work
