### ISSUE TITLE
java-dogstatsd-client is not 1.6 compliant

### ISSUE THREAD

**Issue by Rulasmur** [DataDog/java-dogstatsd-client#48]
ThreadLocalRandom ( used: NonBlockingStatsDClient.java:973) was added in 1.7

Commit which added this:
https://github.com/DataDog/java-dogstatsd-client/commit/f2cfb203b3036e74eb3de7851c638078fc12f87f

**Comment by masci** [comment]
We dropped support for 1.6 in version 2.4, see https://github.com/DataDog/java-dogstatsd-client/releases/tag/java-dogstatsd-client-2.4 but you can still use java-dogstatsd-client 2.3.

Closing this as a won't fix.
