### ISSUE TITLE
NonBlockingStatsDClient loses events

### ISSUE THREAD

**Issue by PolinaRodimova** [DataDog/java-dogstatsd-client#59]
Hey!
I observe that some dd events are geting lost for my application.
It happens with last events before shutdown.
I checked the code of NonBlockingStatsDClient and I see that method "stop" stops sending events even the queue is not empty. 
I could reproduce it with this test:
```
    @Test(timeout = 15000L)
    public void shutdown2() throws Exception {
        final int port = 17257;
        final NonBlockingStatsDClient client = new NonBlockingStatsDClient("my.prefix.shutdownTest", "localhost", port);
        final DummyStatsDServer server = new DummyStatsDServer(port);
        final ExecutorService executorService = Executors.newFixedThreadPool(16);

        for (int i = 0; i < 1000; i++) {
            executorService.submit(new Runnable() {
                @Override
                public void run() {
                    for (int i = 0; i < 1000; i++) {
                        client.count("mycounter", 5);
                    }
                }
            });
        }
        executorService.shutdown();
        executorService.awaitTermination(5, TimeUnit.SECONDS);
        client.stop();
        assertEquals(1000 * 1000, server.messagesReceived().size());
    }

```

I propose to implement graceful shutdown: wait until the queue is empty or timeout happens.
Please see my fix : https://github.com/DataDog/java-dogstatsd-client/pull/58

**Comment by lvicentesanchez** [comment]
Are you going to make a release with this fix soon? If not, is there any snapshot I could use to check if this changes fixes our problems?

**Comment by guizmaii** [comment]
Any news about the release of a new version containing this fix ? Thanks :)

**Comment by arbll** [comment]
Related PR got merged, closing.
