### ISSUE TITLE
Support Posting Events / Sync with Upstream Branch

### ISSUE THREAD

**Issue by TheJeremyGray** [DataDog/java-dogstatsd-client#6]
I'd like to see this project support the posting of events to dogstatsd the same way the .net client does.
Looks like this was [PR'ed](https://github.com/indeedeng/java-dogstatsd-client/commit/6afa75cc1e6993f815ce544c8739cd32ab5acb9e) into indeedeng/java-dogstatsd-client on march 1st and there hasn't been any activity on this project  for close to a year. 
Can someone pull down the latest changes from the parent repo and build it?  I would be happy to help test.

**Comment by enisher** [comment]
:+1:

**Comment by JohnLZeller** [comment]
Thanks for the ticket on this @TheJeremyGray ! I'm gonna go ahead and prioritize this, since it does indeed look like a good addition.

**Comment by masci** [comment]
Resolved via #7
