### ISSUE TITLE
Allow address resolution before send

### ISSUE THREAD

**Issue by fakraemer** [DataDog/java-dogstatsd-client#8]
The StatsD client currently is not able to cope with address changes on the DNS name throughout its lifetime. We raised indeedeng#26 in order to provide a configuration option for the client to change this behaviour, so that resolution is attempted prior sending data (relying on `java.net.InetAddress`'s DNS cache).

Your fork is consumed by [coursera/metrics-datadog](https://github.com/coursera/metrics-datadog), which is our dependency. We would like to see the above mentioned changes merged in and a release cut, in order to raise a PR against metrics-datadog that allows this configuration to be passed through. Would you prefer me to raise a PR with just the above mentioned changes or would you like to sync with the upstream fork (that would cover DataDog#1 as well afaics)?

**Comment by masci** [comment]
Closed via 8230e1a333cfab0a8466471f8131ad0203a4b0f7
